on:
  push:
    branches:
      - main

jobs:
  
  setup:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - run: npm install -g aws-cdk

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: eu-west-2
          
      - uses: actions/checkout@v4
        
  test:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      
      - working-directory: ./src
        name: Test API
        run: dotnet test ./DotnetHelp.DevTools.Api.Tests/DotnetHelp.DevTools.Api.Tests.csproj --logger "trx;LogFileName=TestResults.trx" --collect:"XPlat Code Coverage"
  
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: [test]
    steps:

      - working-directory: ./src
        name: Build API
        run: docker build . -f ./DotnetHelp.DevTools.Api/Dockerfile -t api_aot_build --output=. --target=final
        
      - working-directory: ./src
        name: Rename
        run: mv ./app/DotnetHelp.DevTools.Api ./app/bootstrap
        
      - working-directory: ./src
        name : Zip
        run: zip -r api.zip ./app/
        
      - name: Upload API
        uses: actions/upload-artifact@v2
        with:
          name: api
          path: ./src/api.zip