on:
  push:
    branches:
      - main
    paths:
      - 'src/DotnetHelp.DevTools.Web/**'
      - 'src/DotnetHelp.DevTools.Shared/**'
      - 'src/DotnetHelp.DevTools.Web.Cdk/**'
      - '.github/workflows/web_deploy.yml'

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: 1

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        name : Checkout

      - uses: actions/setup-dotnet@v4
        name : Install dotnet
        with:
          dotnet-version: 8
          
      - name: Tools
        run: dotnet workload install wasm-tools
      
      - working-directory: ./src/DotnetHelp.DevTools.Web
        name: Build
        run: dotnet publish -c Release -o out
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: www
          path: ./src/DotnetHelp.DevTools.Web/out/wwwroot
        
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: production
    permissions:
      contents: read
      id-token: write
    env:
      CERTIFICATE_ARN: ${{ vars.WEB_CERTIFICATE_ARN }}
    steps:
    
      - uses: actions/checkout@v4
        name : Checkout
        
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: www
          path: ./src/DotnetHelp.DevTools.Web/out/wwwroot

      - uses: actions/setup-node@v4
        name : Install node
        with:
          node-version: 20

      - run: npm install -g aws-cdk
        name : Install CDK

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: ${{ secrets.AWS_ROLE }}
            aws-region: eu-west-2
            
      - name : Deploy
        working-directory: ./src/DotnetHelp.DevTools.Web.Cdk
        run: cdk deploy --require-approval never